### ISSUE TITLE
Integrate Danger to lint pull requests

### ISSUE THREAD

**Issue by fuzza** [fuzza/SwiftyJanet#5]

**Comment by fuzza** [comment]
@demalex 
Currently #7 validates only change synchronization between `Cartfile` and `podspec`.
I think we also might want to post basic junit report about unit test results using https://github.com/orta/danger-junit.

Maybe you have some ideas what should we also validate using Danger?

**Comment by demalex** [comment]
@fuzza As an additional option danger could validate changes on `Gemfile`, `Brewfile`, `.travis.yml`. Also, I would like to have minimal commit validation (commit message length and trailing empty line in case if there is commit summary). Maybe it is not so critical now, but still.

As for `danger-junit`, do we really need it? As far as I understood, `codecov` does the same, but only providing the link to view full report at `Codecov`. Or you propose to use `codecov` for PR into `master` and `danger-junit` for all the rest? 

What do you think?

**Comment by fuzza** [comment]
`codecov` just reports coverage info. junit report could be used to report which exact test cases are broken in case of failure

**Comment by fuzza** [comment]
As for config files validation (Gemfile, Brewfile etc.) I'd propose to use danger's `message` command  since I don't really want to restrict or warn such changes. What do you think if we will just highlight these checks to have some kind of pull request increment summary?
