### ISSUE TITLE
Define target code coverage

### ISSUE THREAD

**Issue by fuzza** [fuzza/SwiftyJanet#8]
Need to agree on boundary for unit tests coverage that will be validated by codecov

**Comment by demalex** [comment]
@fuzza Are you talking about coverage boundary for specific increment or in general? Could you please provide a little bit more context?

**Comment by fuzza** [comment]
I meant the some target coverage value for the whole project that we want to keep. 
The idea behind that is to fail the build if overall unit test coverage falls below this value.

**Comment by fuzza** [comment]
Agreed on 80% for now
